### ISSUE TITLE
What are the Lua dependencies?

### ISSUE THREAD

**Issue by SpiritQuaddicted** [shaunlebron/blinky#43]
Hi there!

I tried compiling but got

...
  CC      build/nqsw/sys_dosa.o
  LINK    tyr-quake
build/nqsw/lens.o: In function `L_InitLua':
lens.c:(.text+0x9a0): undefined reference to `luaopen_jit'
collect2: ld returned 1 exit status
make: *** [tyr-quake] Error 1

I am on Archlinux. lua 5.1.4-6  is installed. I did install luajit 1.1.7-1 but it did not help.

**Comment by shaunlebron** [comment]
removed luajit as a dependency, just requires lua
