### ISSUE TITLE
software licensing issue

### ISSUE THREAD

**Issue by jmtd** [shaunlebron/blinky#75]
Hi there, at the moment you've declared this project to be wholly MIT-licensed.

TyrQuake inherits the software license of the underlying Quake source code, which is [GPL-2](http://disenchant.net/git/?p=tyrquake&a=blob&h=2f3289afb5656e59023a4e13e7fa45bf77a51fe9&hb=0ca7766d0fed7e73284b55dd9c6d559c1944c84e&f=gnu.txt). Therefore, the  Quake and TyrQuake bits in *this* repository have to be GPL-2, and cannot be MIT. (This is because the GPL-2 includes extra constraints that the MIT does not).

Perhaps your intention was that your extra bits are MIT? If so, please clarify that. Additionally, any bits of yours which are derivations from the GPL-2 stuff are in murky water. The simplest thing to do would be to declare the whole repository GPL-2.

**Comment by shaunlebron** [comment]
Thanks a lot.  I updated the [license section](https://github.com/shaunlebron/blinky#license) to reflect this.  I want the Lua scripts and fisheye.c (a whole new file) to have a less restrictive license.
