### ISSUE TITLE
Mac binary can't find SDL2

### ISSUE THREAD

**Issue by shaunlebron** [shaunlebron/blinky#76]
from [reddit](http://www.reddit.com/r/gamedev/comments/2ygabj/exploring_peripheral_vision_in_games_using_quake/cp9ce37)

```
Immediately crashes on startup on OS X:
Dyld Error Message: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2 Referenced from: /Users/USER/Documents/*/Blinky.app/Contents/MacOS/Launcher Reason: image not found
```

Reproduced the problem on my 10.8.5 by deleting `/Library/Frameworks/SDL2.Framework` on my machine.  So Blinky.app is not using its bundled SDL2.Framework.  Will have to look at how TyrQuake's Makefile bundle task is working.

Apple Documentation on [Embedding Frameworks](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/CreatingFrameworks.html#//apple_ref/doc/uid/20002258-106880)

**Comment by shaunlebron** [comment]
Also crashing on 10.9.5

**Comment by nsabovic** [comment]
`@rpath` is missing from the binary.
I ran `install_name_tool -add_rpath @executable_path/../Frameworks Blinky.app/Contents/MacOS/Launcher`, that made it search for frameworks in Blinky.app/Frameworks directory in addition to /Library/Frameworks.

**Comment by shaunlebron** [comment]
Awesome :tada:

I'll check if this works later and will add it to the build process.  Thanks!

**Comment by shaunlebron** [comment]
@nsabovic, updated download links.  thanks again
