### ISSUE TITLE
Feature Request: 21:9 resolution support

### ISSUE THREAD

**Issue by wargamesqcf** [shaunlebron/blinky#83]
I have a 21:9 monitor however the largest resolution is only 1080p 16:9.

**Comment by shaunlebron** [comment]
This issue is related to the engine [tyrquake](http://disenchant.net/tyrquake/), which I didn't work on.

You may be able to set the screen size the command line args:

```
$ ./play.sh -width ... -height ...
```

If that doesn't work, try adding the `-window` option.

```
$ ./play.sh -width ... -height ... -window
```

**Comment by wargamesqcf** [comment]
This the windows commands?

**Comment by shaunlebron** [comment]
For Windows:

1. right-click blinky.exe > Create Shortcut.
2. right-click the new shortcut > Properties
3. in the Shortcut tab under Target, add `-window -width <width> -height <height>`

Screenshot:

![blinky-shortcut](https://cloud.githubusercontent.com/assets/116838/17860592/b7494572-6842-11e6-88a0-e57544de9adb.PNG)

**Comment by wargamesqcf** [comment]
Worked just fine thanks.
